# Config file for automatic testing at travis-ci.org
dist: trusty
language: python
python:
  - 3.6
  - 3.5
  - 2.7

matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial

# Command to install dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox
